# Generated by Django 6.0.3 on 2026-04-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolist',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tolist',
            name='stat',
        ),
        migrations.AlterField(
            model_name='tolist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
