# Generated by Django 6.0.3 on 2026-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tolist_age_remove_tolist_stat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='complete',
            field=models.BooleanField(),
        ),
    ]
