# Generated by Django 6.0.3 on 2026-04-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('Tolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tolist')),
            ],
        ),
    ]
