# Generated by Django 6.0.3 on 2026-04-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_createuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
