# Generated by Django 6.0.3 on 2026-04-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('complete', models.BooleanField()),
                ('tolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tolist')),
            ],
        ),
    ]
