# Generated by Django 6.0.3 on 2026-04-14 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('Tolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tolist')),
            ],
        ),
    ]
