# Generated by Django 6.0.3 on 2026-04-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
