# Generated by Django 6.0.3 on 2026-04-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_loginuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
    ]
